# Generated by Django 4.0 on 2022-01-03 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('create_until', models.DateTimeField(auto_now_add=True, verbose_name='Create_until')),
                ('status', models.CharField(choices=[('new', 'new'), ('in_progress', 'in progress'), ('done', 'done')], default='new', max_length=50)),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
                'db_table': 'Tasks',
            },
        ),
    ]
