# Generated by Django 4.0 on 2022-01-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_task_create_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create_until',
            field=models.DateField(verbose_name='Create_until'),
        ),
    ]
