# Generated by Django 4.0 on 2022-01-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='detailed_description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='detailed_description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_until',
            field=models.DateField(blank=True, null=True, verbose_name='Create_until'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('in_progress', 'in progress'), ('done', 'done')], default='new', max_length=15),
        ),
    ]
